"""
Critic Agents - Validate Analysis Quality

Critic agents evaluate the quality of threat assessments generated by AnalystAgents.

Available Critics:
- **Architect**: Validates threat model completeness and control design
- **Tester**: Validates MITRE mappings and internal consistency
- **Red Teamer**: Validates control effectiveness and exploit difficulty

All critics:
- Use LLM-based assessment (not deterministic)
- Return confidence adjustments (not new recommendations)
- Focus on validation (is the analysis good?) not generation (what threats exist?)

Version: 1.0 (Phase 3D)
"""

from chatbot.modules.agents.critics.architect_critic import (
    EnhancedArchitectCritic,
    create_architect_agent,
    ARCHITECT_RUBRIC,
    ARCHITECT_SYSTEM_PROMPT
)

from chatbot.modules.agents.critics.tester_critic import (
    TesterCritic,
    create_tester_agent,
    create_tester_prompt,
    TESTER_RUBRIC,
    TESTER_SYSTEM_PROMPT
)

from chatbot.modules.agents.critics.red_teamer_critic import (
    RedTeamerCritic,
)

__all__ = [
    # Architect
    "EnhancedArchitectCritic",
    "create_architect_agent",
    "ARCHITECT_RUBRIC",
    "ARCHITECT_SYSTEM_PROMPT",

    # Tester
    "TesterCritic",
    "create_tester_agent",
    "create_tester_prompt",
    "TESTER_RUBRIC",
    "TESTER_SYSTEM_PROMPT",

    # Red Teamer
    "RedTeamerCritic",
]
