"""
Critic Agents - Validate Analysis Quality (Phase 3D)

Critic agents evaluate the quality of threat assessments generated by deterministic analysis.

VALIDATION-ONLY CONTRACT:
- Critics VALIDATE existing analysis (do NOT generate new threats/controls)
- Critics ADJUST confidence (-0% to -10%) based on validation quality
- Critics REQUIRE prerequisites (fail-fast if missing)
- Critics FOCUS on "Is the analysis good?" NOT "What threats exist?"

Available Critics:
- **Architect**: Validates threat model completeness and control design
  - Prerequisites: ground_truth.json + 10 artifacts
  - Output: Design quality score (0-100) + confidence adjustment

- **Tester**: Validates MITRE mappings and internal consistency
  - Prerequisites: 04_architect_critique.json + artifacts
  - Output: Validation quality score (0-100) + confidence adjustment

- **Red Teamer**: Validates control effectiveness and exploit difficulty
  - Prerequisites: 05_tester_critique.json + artifacts + ground_truth.json
  - Output: Exploit difficulty score (0-100) + confidence adjustment

Sequential Chain (enforced by MoEOrchestrator):
  Deterministic → Architect → Tester → Red Team → Orchestrator
  (Each requires previous output or fails)

Version: 3.0 (Phase 3D Week 2 - Validation-only refactor)
"""

from chatbot.modules.agents.critics.architect_critic import (
    EnhancedArchitectCritic,
    create_architect_agent,
    ARCHITECT_RUBRIC,
    ARCHITECT_SYSTEM_PROMPT
)

from chatbot.modules.agents.critics.tester_critic import (
    TesterCritic,
    create_tester_agent,
    create_tester_prompt,
    TESTER_RUBRIC,
    TESTER_SYSTEM_PROMPT
)

from chatbot.modules.agents.critics.red_teamer_critic import (
    RedTeamerCritic,
)

from chatbot.modules.agents.critics.blackhat_critic import (
    BlackhatCritic,
)

__all__ = [
    # Architect
    "EnhancedArchitectCritic",
    "create_architect_agent",
    "ARCHITECT_RUBRIC",
    "ARCHITECT_SYSTEM_PROMPT",

    # Tester
    "TesterCritic",
    "create_tester_agent",
    "create_tester_prompt",
    "TESTER_RUBRIC",
    "TESTER_SYSTEM_PROMPT",

    # Red Teamer
    "RedTeamerCritic",

    # Blackhat (Layer 2D)
    "BlackhatCritic",
]
