"""
Cloud Infrastructure Threat Pattern — CAVEAT + CCM Framework

Detects cloud-specific threats using the CSA CAVEAT framework:
- 60+ cloud attack techniques with CSP-specific context
- AWS / Azure / GCP targeted mitigations and detection guidance
- MITRE ATT&CK cloud sub-technique mapping (T1xxx.00x)

Compliance layer via CSA CCM v4.1 → ATT&CK mapping (CTID):
- get_ccm_controls(threats) returns CCM control IDs for all detected T#### IDs
- Each CCM control includes SSRM layer (shared/csc/csp) and SG SSP prefix hint

Data sources:
  chatbot/data/caveat/caveat_techniques.yaml      — generated by fetch_caveat.py
  chatbot/data/caveat/caveat_mitre_mapping.yaml   — hand-authored MITRE bridge
  chatbot/data/ccm/ccm_by_technique.yaml          — generated by fetch_ccm.py

VERSION: 1.1 — Added CCM compliance enrichment
"""

import logging
from dataclasses import dataclass
from typing import Dict, List, Optional, Set

from chatbot.modules.pattern_registry import ThreatPattern
from chatbot.modules.caveat_helper import get_caveat_helper
from chatbot.modules.ccm_helper import get_ccm_helper

logger = logging.getLogger(__name__)


@dataclass
class _CloudPatternDefaults:
    """Fallback defaults matching CloudPatternSettings — used when pydantic is unavailable."""
    base_risk_iam_abuse: int = 80
    base_risk_data_exposure: int = 75
    base_risk_api_abuse: int = 70
    base_risk_compute_abuse: int = 65
    base_risk_network_lateral: int = 60
    base_risk_supply_chain: int = 65
    base_risk_logging_gaps: int = 60
    reduce_mfa: int = 20
    reduce_least_privilege: int = 15
    reduce_privileged_access_management: int = 15
    reduce_iam_audit: int = 10
    reduce_encryption: int = 15
    reduce_bucket_policy: int = 20
    reduce_dlp: int = 10
    reduce_waf: int = 15
    reduce_api_gateway_auth: int = 20
    reduce_network_segmentation: int = 20
    reduce_cloudtrail: int = 20
    reduce_siem: int = 10
    floor_iam_no_mfa_pam: int = 75
    floor_data_no_encryption_policy: int = 70
    floor_logging_no_trail_siem: int = 60
    priority_threshold_iam: int = 75
    priority_threshold_data: int = 70
    priority_threshold_api: int = 65
    priority_threshold_compute: int = 60
    priority_threshold_network: int = 60
    priority_threshold_logging: int = 55

# ── Threat categories covered by this pattern ─────────────────────────────────
THREAT_CATEGORIES = [
    "iam_abuse",       # Privilege escalation, credential theft
    "data_exposure",   # Storage misconfiguration, object ACL abuse
    "api_abuse",       # Gateway abuse, metadata SSRF, session theft
    "compute_abuse",   # Serverless, container escape, cryptomining
    "network_lateral", # VPC peering, cross-account, boundary bridging
    "supply_chain",    # Container image poisoning, deployment tool abuse
    "logging_gaps",    # Audit log tampering, CloudTrail disable
]

# ── Component → category relevance (static — not user-tunable) ───────────────
_COMPONENT_CATEGORIES: Dict[str, List[str]] = {
    "iam":         ["iam_abuse"],
    "storage":     ["data_exposure"],
    # api and compute nodes implicitly have IAM roles attached in all cloud providers
    # (every Lambda/EC2/container has an execution role; every API gateway has an
    # authoriser or caller identity). Model iam_abuse here so it surfaces even when
    # the diagram doesn't draw an explicit IAM node.
    "api":         ["api_abuse", "data_exposure", "iam_abuse"],
    "compute":     ["compute_abuse", "supply_chain", "iam_abuse"],
    "network":     ["network_lateral"],
    "logging":     ["logging_gaps"],
    "database":    ["data_exposure", "iam_abuse"],
    "supply_chain":["supply_chain"],
}


def _build_scoring_tables(cfg) -> tuple[Dict, Dict, Dict]:
    """
    Build _BASE_RISK, _CONTROL_REDUCTIONS, _MISSING_CONTROL_FLOORS from
    a CloudPatternSettings instance (from get_settings().cloud_pattern).

    Called once at CloudPattern.__init__ so changes to settings take effect
    on the next registry reset (same lifecycle as other pattern config).
    """
    base_risk = {
        "iam_abuse":       cfg.base_risk_iam_abuse,
        "data_exposure":   cfg.base_risk_data_exposure,
        "api_abuse":       cfg.base_risk_api_abuse,
        "compute_abuse":   cfg.base_risk_compute_abuse,
        "network_lateral": cfg.base_risk_network_lateral,
        "supply_chain":    cfg.base_risk_supply_chain,
        "logging_gaps":    cfg.base_risk_logging_gaps,  # default 60
    }

    control_reductions = {
        "iam_abuse": {
            "mfa":                          cfg.reduce_mfa,
            "least_privilege":              cfg.reduce_least_privilege,
            "privileged_access_management": cfg.reduce_privileged_access_management,
            "iam_audit":                    cfg.reduce_iam_audit,
        },
        "data_exposure": {
            "encryption":   cfg.reduce_encryption,
            "bucket_policy":cfg.reduce_bucket_policy,
            "dlp":          cfg.reduce_dlp,
            "data_classification": 10,  # minor, not exposed as tunable
        },
        "api_abuse": {
            "waf":             cfg.reduce_waf,
            "api_gateway_auth":cfg.reduce_api_gateway_auth,
            "rate_limiting":   10,
            "tls":             10,
        },
        "compute_abuse": {
            "container_scanning": 15,
            "runtime_security":   15,
            "function_permissions": 10,
        },
        "network_lateral": {
            "network_segmentation": cfg.reduce_network_segmentation,
            "vpc_flow_logs":        10,
            "zero_trust":           15,
        },
        "supply_chain": {
            "image_signing":    15,
            "sbom":             10,
            "pipeline_security":15,
        },
        "logging_gaps": {
            "cloudtrail":   cfg.reduce_cloudtrail,
            "log_integrity":15,
            "siem":         cfg.reduce_siem,
        },
    }

    missing_control_floors = {
        "iam_abuse": [
            {"controls": ["mfa", "privileged_access_management"],
             "floor": cfg.floor_iam_no_mfa_pam,
             "rationale": "No MFA or PAM — credential abuse goes uncontested"}
        ],
        "data_exposure": [
            {"controls": ["encryption", "bucket_policy"],
             "floor": cfg.floor_data_no_encryption_policy,
             "rationale": "No encryption or bucket policy — storage exposure likely"}
        ],
        "logging_gaps": [
            {"controls": ["cloudtrail", "siem"],
             "floor": cfg.floor_logging_no_trail_siem,
             "rationale": "No audit logging — attacker activity invisible after breach"}
        ],
    }

    return base_risk, control_reductions, missing_control_floors


class CloudPattern(ThreatPattern):
    """
    Cloud-specific threat pattern anchored to the CSA CAVEAT framework.

    Adds CSP-targeted attack techniques and mitigations that MITRE ATT&CK
    Enterprise covers only generically.
    """

    def __init__(self):
        super().__init__(name="Cloud Infrastructure (CAVEAT)", version="1.1")
        self._caveat = get_caveat_helper()

        # Load scoring tables from live settings (tunable via /api/v1/config).
        # Fall back to a plain-object default when pydantic/config is unavailable
        # (e.g. lightweight CLI use outside the venv).
        try:
            from chatbot.config.settings import get_settings
            cfg = get_settings().cloud_pattern
        except Exception:
            cfg = _CloudPatternDefaults()

        self._base_risk, self._control_reductions, self._missing_control_floors = (
            _build_scoring_tables(cfg)
        )

        # Cache recommendation thresholds
        self._thresholds = {
            "iam_abuse":       cfg.priority_threshold_iam,
            "data_exposure":   cfg.priority_threshold_data,
            "api_abuse":       cfg.priority_threshold_api,
            "compute_abuse":   cfg.priority_threshold_compute,
            "network_lateral": cfg.priority_threshold_network,
            "logging_gaps":    cfg.priority_threshold_logging,
        }

        if self._caveat.is_loaded:
            logger.info(
                f"{self.name} v{self.version} initialized "
                f"({len(self._caveat.get_techniques())} CAVEAT techniques, "
                f"base_risk_iam={cfg.base_risk_iam_abuse})"
            )
        else:
            logger.warning(
                f"{self.name} initialized without CAVEAT data — "
                "run: python3 scripts/data/fetch_caveat.py"
            )

    # ── ThreatPattern interface ───────────────────────────────────────────────

    def get_name(self) -> str:
        return "Cloud Infrastructure (CAVEAT)"

    def get_threat_categories(self) -> List[str]:
        return THREAT_CATEGORIES

    def get_supported_architecture_types(self) -> Set[str]:
        return {"cloud", "cloud_native", "web_app", "hybrid_cloud"}

    def assess_threat(self, node: str, context: Dict) -> Dict:
        """
        Assess cloud threats for a node using CAVEAT techniques.

        Returns a dict keyed by threat category:
            {"iam_abuse": {"risk": int, "rationale": str,
                           "techniques": List[str], "affected_nodes": List[str]}}
        """
        component = self._detect_cloud_component(node)
        if component == "unknown":
            return {}

        logger.debug(f"{self.name}: node='{node}' → component_type='{component}'")

        controls = [c.lower().replace(" ", "_") for c in context.get("controls_present", [])]
        csp = context.get("csp")

        applicable_categories = _COMPONENT_CATEGORIES.get(component, [])
        caveat_titles = self._caveat.get_techniques_for_component(component)

        threats: Dict[str, Dict] = {}

        for category in applicable_categories:
            risk, rationale = self._score_category(category, component, controls)
            if risk <= 0:
                continue

            # Gather MITRE T#### IDs for relevant CAVEAT techniques
            techniques: List[str] = []
            for title in caveat_titles:
                techniques.extend(self._caveat.get_mitre_ids(title))
            techniques = list(dict.fromkeys(techniques))  # Unique, ordered

            # Append CSP hint to rationale when available
            if csp:
                mitigations = []
                for title in caveat_titles[:2]:
                    mits = self._caveat.get_mitigations(title, csp=csp)
                    mitigations.extend(mits[:1])
                if mitigations:
                    rationale += f" | {csp.upper()} mitigation: {mitigations[0][:120]}"

            threats[category] = {
                "risk": risk,
                "rationale": rationale,
                "techniques": techniques[:8],
                "affected_nodes": [node],
                "caveat_techniques": caveat_titles[:5],
                "csp": csp,
            }

        return threats

    def recommend_controls(self, threats: Dict, context: Dict) -> List[str]:
        """Return CSP-aware control recommendations based on assessed threats."""
        priority: List[str] = []
        medium: List[str] = []
        t = self._thresholds

        if "iam_abuse" in threats:
            risk = threats["iam_abuse"]["risk"]
            if risk >= t["iam_abuse"]:
                priority.extend(["mfa", "least_privilege", "privileged_access_management"])
            if risk >= t["iam_abuse"] - 10:
                medium.extend(["iam_audit", "session_management"])

        if "data_exposure" in threats:
            risk = threats["data_exposure"]["risk"]
            if risk >= t["data_exposure"]:
                priority.extend(["encryption", "bucket_policy"])
            if risk >= t["data_exposure"] - 10:
                medium.extend(["dlp", "data_classification"])

        if "api_abuse" in threats:
            risk = threats["api_abuse"]["risk"]
            if risk >= t["api_abuse"]:
                priority.extend(["api_gateway_auth", "waf"])
            if risk >= t["api_abuse"] - 10:
                medium.extend(["rate_limiting", "tls"])

        if "compute_abuse" in threats:
            risk = threats["compute_abuse"]["risk"]
            if risk >= t["compute_abuse"]:
                priority.extend(["container_scanning", "runtime_security"])
            medium.append("function_permissions")

        if "network_lateral" in threats:
            risk = threats["network_lateral"]["risk"]
            if risk >= t["network_lateral"]:
                priority.append("network_segmentation")
            medium.extend(["vpc_flow_logs", "zero_trust"])

        if "supply_chain" in threats:
            priority.extend(["image_signing", "pipeline_security"])
            medium.append("sbom")

        if "logging_gaps" in threats:
            risk = threats["logging_gaps"]["risk"]
            if risk >= t["logging_gaps"]:
                priority.append("cloudtrail")
            medium.extend(["log_integrity", "siem"])

        controls = list(dict.fromkeys(priority + medium))
        logger.info(f"{self.name}: Recommended {len(controls)} controls")
        return controls

    def validate(self, ground_truth: Dict) -> Dict:
        """Validate completeness of cloud threat assessment."""
        checks: Dict[str, bool] = {}
        issues: List[str] = []

        cloud_threats = ground_truth.get("cloud_assessment", {})
        if not cloud_threats:
            cloud_threats = (
                ground_truth.get("pattern_assessments", {})
                .get("Cloud Infrastructure (CAVEAT)", {})
            )

        checks["cloud_components_detected"] = len(cloud_threats) > 0
        if not checks["cloud_components_detected"]:
            issues.append("No cloud components detected in architecture")

        high_risk_cats = [c for c, d in cloud_threats.items()
                          if isinstance(d, dict) and d.get("risk", 0) > 70]
        cloud_controls = ground_truth.get("cloud_controls_recommended", [])
        checks["controls_for_high_risk"] = bool(cloud_controls) if high_risk_cats else True
        if high_risk_cats and not cloud_controls:
            issues.append(f"High-risk categories but no controls recommended: {high_risk_cats}")

        checks["techniques_mapped"] = any(
            isinstance(d, dict) and d.get("techniques")
            for d in cloud_threats.values()
        )
        if not checks["techniques_mapped"] and cloud_threats:
            issues.append("No MITRE techniques mapped for cloud threats")

        checks["caveat_data_available"] = self._caveat.is_loaded
        if not checks["caveat_data_available"]:
            issues.append("CAVEAT data not loaded — run: python3 scripts/data/fetch_caveat.py")

        passed = sum(1 for v in checks.values() if v)
        confidence = passed / len(checks) if checks else 0.0

        return {
            "passed": confidence >= 0.75,
            "confidence": confidence,
            "checks": checks,
            "issues": issues,
        }

    def get_ccm_controls(self, threats: Dict, csp: Optional[str] = None) -> List[Dict]:
        """
        Return CSA CCM v4.1 controls that address the detected threats.

        Uses the T#### IDs already in each threat category's 'techniques' list
        to look up matching CCM controls via ccm_helper. Controls covering more
        techniques are ranked first.

        Each returned dict:
          {ccm_id, description, group, comments, ssrm_layer, ssp_prefixes,
           technique_count, mitre_techniques}

        This method is additive — does not replace assess_threat() output.
        """
        if not threats:
            return []

        # Collect all unique technique IDs across all threat categories
        all_techniques: List[str] = []
        for data in threats.values():
            if isinstance(data, dict):
                all_techniques.extend(data.get("techniques", []))
        all_techniques = list(dict.fromkeys(all_techniques))

        if not all_techniques:
            return []

        ccm = get_ccm_helper()
        if not ccm.is_loaded:
            logger.warning(f"{self.name}: CCM data not loaded — run: python3 scripts/data/fetch_ccm.py")
            return []

        controls = ccm.get_controls_for_techniques(all_techniques)

        # Annotate with technique count and the techniques they cover
        result = []
        for ctrl in controls:
            cid = ctrl["ccm_id"]
            info = ccm.get_control_info(cid) or {}
            covered = [t for t in all_techniques if t in (info.get("techniques") or [])]
            result.append({
                **ctrl,
                "technique_count": len(covered),
                "mitre_techniques": covered,
            })

        logger.info(f"{self.name}: get_ccm_controls() → {len(result)} CCM controls for {len(all_techniques)} techniques")
        return result

    # ── Internals ─────────────────────────────────────────────────────────────

    def _detect_cloud_component(self, node: str) -> str:
        """Map a node name to a cloud component type via keyword matching."""
        node_lower = node.lower()

        keyword_map = [
            ("iam",     ["iam", "role", "policy", "permission", "identity",
                         "rbac", "service_account", "service account"]),
            ("storage", ["s3", "blob", "gcs", "storage", "bucket", "object store",
                         "data lake", "data store"]),
            # CDN/SaaS delivery — treated as api (config-level risk: misconfigured
            # origins, WAF bypass, token leakage); real-CSP examples: CloudFront,
            # Azure Front Door, GCP Cloud CDN, Cloudflare, Akamai, Fastly
            ("api",     ["api_gateway", "api gateway", "apigw", "api", "endpoint",
                         "alb", "elb", "load balancer",
                         "cloudfront", "front door", "cloud cdn",
                         "cdn", "cloudflare", "akamai", "fastly",
                         "reverse proxy", "waf gateway"]),
            ("compute", ["ec2", "vm", "virtual machine", "instance",
                         "lambda", "function", "serverless",
                         "container", "ecs", "eks", "gke", "aks", "kubernetes", "k8s",
                         "fargate", "cloud run",
                         # Generic IaaS/PaaS service labels — default to compute
                         # unless a more specific keyword matches first.
                         # Include both spaced and camelCase/concatenated forms since
                         # the mermaid parser collapses node label spaces.
                         "cloud application", "cloudapplication",
                         "cloud app", "cloudapp",
                         "cloud service", "cloudservice",
                         "cloud workload", "cloudworkload",
                         "cloud server", "cloudserver",
                         "cloud host", "cloudhost",
                         "app service", "appservice",
                         "web app", "webapp",
                         "web service", "webservice",
                         "microservice", "backend service", "backend",
                         "paas", "iaas", "hosted service"]),
            ("database",["rds", "dynamodb", "cosmos", "spanner", "aurora", "sql",
                         "postgres", "mysql", "redis", "elasticache"]),
            ("network", ["vpc", "vnet", "subnet", "firewall", "nsg", "security_group",
                         "security group", "peering", "transit_gateway", "interconnect"]),
            ("logging", ["cloudtrail", "cloudwatch", "azure_monitor", "azure monitor",
                         "stackdriver", "cloud logging", "logging", "audit", "siem"]),
        ]

        for component_type, keywords in keyword_map:
            if any(kw in node_lower for kw in keywords):
                return component_type
        return "unknown"

    def _score_category(self, category: str, component: str,
                         controls: List[str]) -> tuple[int, str]:
        """Return (risk_score, rationale) for a category/component pair."""
        risk = self._base_risk.get(category, 50)
        rationale_parts: List[str] = []

        # Apply control reductions
        reductions = self._control_reductions.get(category, {})
        for ctrl, reduction in reductions.items():
            if ctrl in controls:
                risk -= reduction
                rationale_parts.append(f"{ctrl} reduces {category} risk by {reduction}")

        # Apply missing-control floors
        for floor_rule in self._missing_control_floors.get(category, []):
            required = floor_rule["controls"]
            if all(c not in controls for c in required):
                if risk < floor_rule["floor"]:
                    risk = floor_rule["floor"]
                rationale_parts.append(floor_rule["rationale"])

        risk = max(0, min(100, risk))

        if not rationale_parts:
            rationale_parts.append(
                f"{component} component exposed to {category.replace('_', ' ')} attacks"
            )

        return risk, " | ".join(rationale_parts)
