"""
TA-Wiz Routes

POST /api/v1/ta-wiz/ask  — SSE streaming chat grounded in workspace report files.

Context strategy: load actual generated files per architecture (markdown + mmd +
selective JSON fields), namespace each with box-drawing boundaries to prevent
cross-architecture fact bleed.  No embeddings, no RAG — just the reports passed
directly to the LLM (Bedrock Sonnet has a 200K token window; a 10-arch workspace
is ~95K tokens).

Model selection goes through HarnessModelGuardian.resolve("ta_wiz") — the sole
model broker.  Configure via AGENT_MODEL_TA_WIZ in .env.
"""

import asyncio
import json
from pathlib import Path
from typing import AsyncGenerator, List, Optional

from fastapi import APIRouter, Depends
from fastapi.responses import StreamingResponse

from chatbot.api.dependencies import verify_api_key
from chatbot.api.models.requests import TAWizAskRequest
from chatbot.api.streaming import SSEStream

router = APIRouter(prefix="/api/v1/ta-wiz", tags=["ta-wiz"])

# ---------------------------------------------------------------------------
# Source files loaded per architecture (in order)
# ---------------------------------------------------------------------------
_SOURCE_FILES = [
    ("01_executive_summary.md", "Executive Summary"),
    ("09_threat_model.md",       "Threat Model"),
    ("10_adr_report.md",         "ADR / Controls"),
    ("before.mmd",               "Architecture Diagram (Mermaid)"),
]

# JSON files: (filename, label, keys_to_extract)
_JSON_SOURCES = [
    (
        "ground_truth.json",
        "Key Metrics",
        ["expected_risk_score", "expected_defensibility", "confidence",
         "controls_missing", "controls_present", "techniques"],
    ),
    (
        "07_moe_orchestrator.json",
        "Expert Consensus (MoE)",
        ["critical_recommendations", "high_recommendations", "confidence_delta"],
    ),
    (
        "06_red_team_critique.json",
        "Red Team Perspective",
        ["exploitable_gaps", "recommended_controls"],
    ),
    (
        "08_scrum_master.json",
        "ScrumMaster",
        ["synthesis_note", "action_plan", "redesign_signal"],
    ),
]

_ADR_MAX_BYTES = 30 * 1024  # skip 10_adr_report.md if >30 KB

_SYSTEM_PROMPT = """\
You are TA-Wiz, a threat modelling advisor embedded in ThreatAssessor.
You have been given the full threat assessment reports for a workspace of architectures.
These reports were generated by RAPIDS threat scoring, MITRE ATT&CK mapping, and MoE expert review.

Answer as if you conducted this analysis yourself and are now debriefing the architect.
Cite specific architecture names, attack path IDs (AP-1, AP-2...), MITRE technique IDs (T1078...),
and control names where relevant. Identify patterns across architectures when asked about
systemic issues. Be direct and practical.

NAMESPACE RULE: Each architecture's data is enclosed between
  ╔═══ ARCHITECTURE: {name} ═══╗  and  ╚═══ END ARCHITECTURE: {name} ═══╝
boundaries. Never transfer facts, scores, or recommendations between architectures.
If asked about an architecture not present in WORKSPACE SOURCES, reply:
"That architecture is not in the current workspace scope."
Only reference architectures listed in the sources below.\
"""


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _get_report_dir() -> Path:
    from chatbot.config import get_settings
    cfg = get_settings().system.report_dir
    p = Path(cfg)
    return p if p.is_absolute() else Path(__file__).parent.parent.parent.parent / cfg


def _extract_json_keys(path: Path, keys: List[str]) -> dict:
    """Read a JSON file and return only the requested keys (shallow extract)."""
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
        return {k: data[k] for k in keys if k in data}
    except Exception:
        return {}


def load_workspace_context(
    workspace_name: str,
    selected_architectures: Optional[List[str]],
    report_dir: Path,
) -> tuple[str, List[str], int]:
    """Build the namespaced context string for a workspace.

    Returns:
        (context_string, sources_used_list, estimated_char_count)
    """
    ws_path = report_dir / ".workspaces.json"
    if not ws_path.exists():
        return "", [], 0

    workspaces = json.loads(ws_path.read_text(encoding="utf-8"))
    ws = next((w for w in workspaces if w["name"] == workspace_name), None)
    if ws is None:
        return "", [], 0

    arch_names = ws.get("architectures") or []
    if selected_architectures:
        arch_names = [a for a in arch_names if a in selected_architectures]

    sections: List[str] = []
    sources_used: List[str] = []

    for arch in arch_names:
        arch_dir = report_dir / arch
        if not arch_dir.is_dir():
            continue

        parts: List[str] = []

        # Markdown + mmd files
        for filename, label in _SOURCE_FILES:
            file_path = arch_dir / filename
            if not file_path.exists():
                continue
            # Skip large ADR files
            if filename == "10_adr_report.md" and file_path.stat().st_size > _ADR_MAX_BYTES:
                parts.append(f"--- {label} ---\n[File too large — view in Reports tab]\n")
                continue
            try:
                content = file_path.read_text(encoding="utf-8").strip()
                if content:
                    parts.append(f"--- {label} ---\n{content}\n")
            except Exception:
                pass

        # Selective JSON extracts
        for filename, label, keys in _JSON_SOURCES:
            file_path = arch_dir / filename
            if not file_path.exists():
                continue
            extracted = _extract_json_keys(file_path, keys)
            if extracted:
                parts.append(
                    f"--- {label} ---\n"
                    + json.dumps(extracted, separators=(",", ":"))
                    + "\n"
                )

        if parts:
            section = (
                f"╔═══ ARCHITECTURE: {arch} ═══╗\n"
                + "\n".join(parts)
                + f"╚═══ END ARCHITECTURE: {arch} ═══╝\n"
            )
            sections.append(section)
            sources_used.append(arch)

    context = "\n".join(sections)
    return context, sources_used, len(context)


def _format_history(history) -> str:
    if not history:
        return ""
    lines = []
    for msg in history:
        prefix = "User" if msg.role == "user" else "TA-Wiz"
        lines.append(f"{prefix}: {msg.content}")
    return "\nCONVERSATION HISTORY:\n" + "\n".join(lines) + "\n"


def _call_llm(question: str, context: str, history_text: str, model: Optional[str]) -> str:
    """Blocking LLM call — run via run_in_executor."""
    from agentic.llm_client import LLMClient
    client = LLMClient()
    user_prompt = (
        f"WORKSPACE SOURCES:\n{context}\n"
        f"{history_text}"
        f"\nCURRENT QUESTION: {question}"
    )
    resp = client.generate(
        prompt=user_prompt,
        system_message=_SYSTEM_PROMPT,
        model=model,
        max_tokens=2000,
    )
    return resp.content, resp.model


async def _ta_wiz_stream(
    payload: TAWizAskRequest,
    report_dir: Path,
) -> AsyncGenerator[str, None]:
    """SSE generator for TA-Wiz chat."""

    yield await SSEStream.send_progress("loading", 10, "Loading workspace sources…")

    context, sources_used, char_count = load_workspace_context(
        payload.workspace_name,
        payload.selected_architectures,
        report_dir,
    )

    if not sources_used:
        yield await SSEStream.send_error(
            "No sources loaded",
            f"Workspace '{payload.workspace_name}' not found or has no accessible architectures.",
        )
        return

    approx_tokens = char_count // 4
    yield await SSEStream.send_progress(
        "loaded", 40,
        f"Sources loaded — {len(sources_used)} architecture(s), ~{approx_tokens:,} tokens estimated",
    )

    # Resolve model via Guardian
    model: Optional[str] = None
    try:
        from chatbot.harness.controller import HarnessModelGuardian
        guardian = HarnessModelGuardian()
        model = guardian.resolve("ta_wiz")
    except Exception:
        pass

    yield await SSEStream.send_progress("thinking", 50, "TA-Wiz is reading the reports…")

    history_text = _format_history(payload.history)

    loop = asyncio.get_event_loop()
    try:
        answer, model_used = await loop.run_in_executor(
            None,
            lambda: _call_llm(payload.question, context, history_text, model),
        )
    except Exception as e:
        yield await SSEStream.send_error("LLM call failed", str(e))
        return

    yield await SSEStream.send_progress("done", 95, "Answer ready")
    yield await SSEStream.send_complete({
        "answer":       answer,
        "model":        str(model_used),
        "sources_used": sources_used,
        "tokens_est":   approx_tokens,
    })


# ---------------------------------------------------------------------------
# Endpoint
# ---------------------------------------------------------------------------

@router.post("/ask")
async def ta_wiz_ask(
    payload: TAWizAskRequest,
    _: str = Depends(verify_api_key),
) -> StreamingResponse:
    """Stream a TA-Wiz response grounded in the workspace's report files.

    Sends SSE events: progress (×3) → complete | error.
    complete payload: {answer, model, sources_used, tokens_est}
    """
    report_dir = _get_report_dir()
    return StreamingResponse(
        _ta_wiz_stream(payload, report_dir),
        media_type="text/event-stream",
        headers={
            "Cache-Control":    "no-cache",
            "X-Accel-Buffering": "no",
        },
    )
