"""
CAVEAT Helper - Cloud Adversarial, Vulnerability, Exploitation, and Threat

Provides access to CSA CAVEAT cloud threat techniques:
- 60+ cloud-specific attack techniques
- CSP-specific mitigations (AWS / Azure / GCP)
- CSP-specific detection guidance
- MITRE ATT&CK T#### mapping (via caveat_mitre_mapping.yaml)

Data source: https://github.com/CloudSecurityAlliance-WG/CAVEaT (CC0-1.0)
Refresh: python3 scripts/data/fetch_caveat.py

Usage:
    caveat = get_caveat_helper()
    techs = caveat.get_techniques()
    mits = caveat.get_mitigations("IAM Abuse", csp="aws")
    ids = caveat.get_mitre_ids("IAM Abuse")
"""

import logging
from pathlib import Path
from typing import Dict, List, Optional

import yaml

logger = logging.getLogger(__name__)

_DATA_DIR = Path(__file__).parent.parent / "data" / "caveat"


class CaveatHelper:
    """
    Helper for CAVEAT (CSA) cloud threat framework.

    Loads caveat_techniques.yaml (generated by scripts/data/fetch_caveat.py)
    and caveat_mitre_mapping.yaml (hand-authored, committed to git).
    """

    def __init__(self, data_dir: Optional[Path] = None):
        self._dir = data_dir or _DATA_DIR
        self._techniques: List[Dict] = []
        self._by_title: Dict[str, Dict] = {}
        self._mitre_map: Dict[str, Dict] = {}
        self._loaded = False
        self._load()

    def _load(self) -> None:
        tech_path = self._dir / "caveat_techniques.yaml"
        map_path = self._dir / "caveat_mitre_mapping.yaml"

        if not tech_path.exists():
            logger.warning(
                f"CAVEAT techniques file not found at {tech_path}. "
                "Run: python3 scripts/data/fetch_caveat.py"
            )
            return

        with open(tech_path, "r", encoding="utf-8") as fh:
            data = yaml.safe_load(fh)
        self._techniques = data.get("techniques", [])
        self._by_title = {t["title"]: t for t in self._techniques}

        if map_path.exists():
            with open(map_path, "r", encoding="utf-8") as fh:
                self._mitre_map = yaml.safe_load(fh) or {}

        logger.info(
            f"CAVEAT loaded: {len(self._techniques)} techniques, "
            f"{len(self._mitre_map)} MITRE mappings"
        )
        self._loaded = True

    @property
    def is_loaded(self) -> bool:
        return self._loaded

    # -----------------------------------------------------------------------
    # Public API
    # -----------------------------------------------------------------------

    def get_techniques(self) -> List[Dict]:
        """Return all CAVEAT technique dicts."""
        return self._techniques

    def get_by_title(self, title: str) -> Optional[Dict]:
        """Return a single technique dict by exact title, or None."""
        return self._by_title.get(title)

    def get_by_keyword(self, keyword: str) -> List[Dict]:
        """
        Return techniques whose keywords list contains keyword (case-insensitive).

        Each technique's 'keywords' field is auto-derived from its title.
        """
        kw = keyword.lower()
        return [
            t for t in self._techniques
            if kw in t.get("keywords", [])
            or kw in t.get("title", "").lower()
            or kw in t.get("description", "").lower()
        ]

    def get_mitre_ids(self, title: str) -> List[str]:
        """Return MITRE ATT&CK T#### IDs mapped to this CAVEAT technique."""
        entry = self._mitre_map.get(title, {})
        return entry.get("mitre_techniques", [])

    def is_caveat_native(self, title: str) -> bool:
        """Return True if technique has no direct MITRE equivalent."""
        entry = self._mitre_map.get(title, {})
        return bool(entry.get("caveat_native", False))

    def get_mitigations(self, title: str, csp: Optional[str] = None) -> List[str]:
        """
        Return mitigation strings for a technique.

        Args:
            title: CAVEAT technique title
            csp:   Optional CSP filter — "aws", "azure", "gcp".
                   If None, returns generic + all CSP mitigations.
        """
        tech = self._by_title.get(title)
        if not tech:
            return []

        if csp == "aws":
            return tech.get("mitigations_aws", []) + tech.get("mitigations_generic", [])
        if csp == "azure":
            return tech.get("mitigations_azure", []) + tech.get("mitigations_generic", [])
        if csp == "gcp":
            return tech.get("mitigations_gcp", []) + tech.get("mitigations_generic", [])

        # No CSP filter — return all
        return (
            tech.get("mitigations_generic", [])
            + tech.get("mitigations_aws", [])
            + tech.get("mitigations_azure", [])
            + tech.get("mitigations_gcp", [])
        )

    def get_detection(self, title: str, csp: Optional[str] = None) -> List[str]:
        """
        Return detection guidance for a technique.

        Args:
            title: CAVEAT technique title
            csp:   Optional CSP filter — "aws", "azure", "gcp".
        """
        tech = self._by_title.get(title)
        if not tech:
            return []

        if csp == "aws":
            return tech.get("detection_aws", []) + tech.get("detection_generic", [])
        if csp == "azure":
            return tech.get("detection_azure", []) + tech.get("detection_generic", [])
        if csp == "gcp":
            return tech.get("detection_gcp", []) + tech.get("detection_generic", [])

        return (
            tech.get("detection_generic", [])
            + tech.get("detection_aws", [])
            + tech.get("detection_azure", [])
            + tech.get("detection_gcp", [])
        )

    def get_techniques_for_component(self, component_type: str) -> List[str]:
        """
        Return CAVEAT technique titles relevant to a cloud component type.

        Keyword-based mapping — returns titles, not full dicts.
        """
        component_keywords = {
            "iam": ["iam", "identity", "privilege", "account", "credential", "role",
                    "permission", "authentication", "token", "mfa"],
            "storage": ["storage", "bucket", "object", "blob", "s3", "data"],
            "compute": ["container", "serverless", "function", "lambda", "execution",
                        "resource", "hijacking", "image"],
            "api": ["web", "api", "session", "cookie", "application", "service",
                    "dashboard"],
            "network": ["network", "boundary", "bridging", "sniffing", "lateral"],
            "logging": ["logging", "log", "disable", "audit", "cloudtrail"],
            "supply_chain": ["supply", "software", "deployment", "infrastructure",
                              "compromise", "implant"],
            "database": ["data", "storage", "exfiltration", "cloud"],
        }

        keywords = component_keywords.get(component_type, [])
        if not keywords:
            return []

        matched = set()
        for t in self._techniques:
            title_lower = t["title"].lower()
            desc_lower = t.get("description", "")[:200].lower()
            for kw in keywords:
                if kw in title_lower or kw in desc_lower:
                    matched.add(t["title"])
                    break

        return sorted(matched)


# ---------------------------------------------------------------------------
# Singleton
# ---------------------------------------------------------------------------

_caveat_instance: Optional[CaveatHelper] = None


def get_caveat_helper(data_dir: Optional[Path] = None) -> CaveatHelper:
    """Return the shared CaveatHelper singleton (lazy-loaded on first call)."""
    global _caveat_instance
    if _caveat_instance is None:
        _caveat_instance = CaveatHelper(data_dir=data_dir)
    return _caveat_instance


__all__ = ["CaveatHelper", "get_caveat_helper"]
