"""
SSP Control Enrichment — Singapore Government ICT&SS Control Catalog.

Enriches deterministic-engine control recommendations with policy-grounded context:
  - Named SSP control ID (e.g., AC-1) and catalog section
  - Risk statement explaining why the control matters
  - Implementation recommendation from the official catalog
  - Baseline level (L0 cardinal / L1 basic hygiene / L2 best practice)

Enrichment is additive: existing recommendations are unchanged in content and order.
Only a new `ssp_context` field is added per recommendation.

Usage:
    mapper = SspControlMapper()
    recs = mapper.enrich_recommendations(recs, target_profile="medium_risk_cloud")

Data files (generated by scripts/ingest/scrape_ssp_catalog.py):
    chatbot/data/ssp/cybersecurity_catalog.json
    chatbot/data/ssp/dss_catalog.json
    chatbot/data/ssp/ssp_profiles.json
    chatbot/data/ssp/control_name_mappings.json
"""

import json
import logging
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)

SSP_PROFILES = [
    "low_risk_cloud",
    "low_risk_onprem",
    "medium_risk_cloud",
    "high_risk_cloud_cii",
    "generative_ai",
    "digital_services_others",
    "digital_services_high_impact",
    "sandbox",
]

_LEVEL_LABELS = {
    0: "L0 — Cardinal",
    1: "L1 — Basic Hygiene",
    2: "L2 — Best Practice",
}

_DEFAULT_DATA_DIR = Path(__file__).parent.parent / "data" / "ssp"


class SspControlMapper:
    """
    Enriches control recommendations with Singapore Government SSP control context.

    Thread-safe after __init__ (read-only after loading). Designed as a module-level
    singleton in exhaustive_mitigation_mapper.py.
    """

    def __init__(self, data_dir: Optional[Path] = None, enabled: bool = True):
        self.enabled = enabled
        self._controls: dict[str, dict] = {}   # control_id → full control record
        self._profiles: dict[str, dict] = {}   # control_id → {profile_name: level}
        self._mappings: dict[str, list] = {}   # control_name → [control_ids]
        self._keywords: dict[str, list] = {}   # keyword → [control_ids]
        self._loaded = False

        if enabled:
            self._load(Path(data_dir) if data_dir else _DEFAULT_DATA_DIR)

    def _load(self, data_dir: Path) -> None:
        try:
            cyber_path = data_dir / "cybersecurity_catalog.json"
            dss_path   = data_dir / "dss_catalog.json"
            ssp_path   = data_dir / "ssp_profiles.json"
            map_path   = data_dir / "control_name_mappings.json"

            missing = [p for p in (cyber_path, dss_path, ssp_path, map_path) if not p.exists()]
            if missing:
                logger.info(
                    f"SSP data files not found ({[str(p) for p in missing]}). "
                    "Run scripts/ingest/scrape_ssp_catalog.py to generate them. "
                    "SSP enrichment will be skipped."
                )
                return

            for record in json.loads(cyber_path.read_text()):
                self._controls[record["id"]] = record
            for record in json.loads(dss_path.read_text()):
                self._controls[record["id"]] = record

            self._profiles = json.loads(ssp_path.read_text())

            raw_mappings = json.loads(map_path.read_text())
            self._keywords = raw_mappings.pop("_keyword_fallback", {})
            # Strip metadata keys
            self._mappings = {k: v for k, v in raw_mappings.items() if not k.startswith("_")}

            self._loaded = True
            logger.info(
                f"SSP catalog loaded: {len(self._controls)} controls, "
                f"{len(self._mappings)} name mappings, {len(self._profiles)} profile entries"
            )
        except Exception as e:
            logger.warning(f"SSP catalog load failed: {e}. SSP enrichment will be skipped.")

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def enrich_recommendations(
        self,
        recommendations: list,
        target_profile: str = "low_risk_cloud",
    ) -> list:
        """
        Add `ssp_context` to each recommendation in-place.

        Recommendations list order and all existing fields are unchanged.
        Returns the same list (mutated in-place for efficiency; safe since callers
        reassign the variable anyway).

        Args:
            recommendations: List of control recommendation dicts from the deterministic engine.
            target_profile:  User-declared SSP profile (planning instrument, not computed).
                             One of SSP_PROFILES. Unknown values fall back to "low_risk_cloud".
        """
        if not self.enabled or not self._loaded:
            return recommendations

        if target_profile not in SSP_PROFILES:
            logger.warning(f"Unknown SSP profile '{target_profile}', using 'low_risk_cloud'")
            target_profile = "low_risk_cloud"

        for rec in recommendations:
            control_name = (rec.get("control") or rec.get("name") or "").lower().strip()
            threat_hints = {
                "rapids_threats": rec.get("rapids_threats") or [],
                "dir_category":   rec.get("dir_category") or "",
                "techniques":     rec.get("techniques") or [],
            }
            rec["ssp_context"] = self._build_context(control_name, target_profile, threat_hints)

        return recommendations

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    # Maps RAPIDS threat category → SSP catalog category prefixes most relevant to that threat.
    _THREAT_CATEGORY_AFFINITY: dict[str, list[str]] = {
        "supply_chain":    ["sc", "sd", "st"],      # Software Supply Chain, Secure Dev, Security Testing
        "app_vulns":       ["as", "sd", "cs"],      # Application Security, Secure Dev, Container Security
        "ransomware":      ["br", "dp", "ck"],      # Backup/Recovery, Data Protection, Cryptography
        "phishing":        ["hr", "ns", "ac"],      # Human Resource, Network Security, Access Control
        "insider_threat":  ["ac", "dp", "lm"],      # Access Control, Data Protection, Logging/Monitoring
        "dos":             ["rs", "ns", "lm"],      # Resiliency, Network Security, Logging/Monitoring
    }

    # Maps DIR category → preferred SSP catalog prefixes
    _DIR_AFFINITY: dict[str, list[str]] = {
        "detect":     ["lm", "st"],
        "isolate":    ["ac", "ns", "dp"],
        "respond":    ["br", "rs"],
        "prevention": ["as", "is", "sd", "sc"],
    }

    def _build_context(
        self,
        control_name: str,
        profile: str,
        threat_hints: Optional[dict] = None,
    ) -> Optional[dict]:
        """Return ssp_context dict or None if no match."""
        matched = self._lookup_ssp_controls(control_name, profile)
        if not matched:
            return None

        # Rerank candidates using threat/DIR context so the most relevant
        # SSP control surfaces as primary instead of blindly taking lowest level.
        if threat_hints and len(matched) > 1:
            matched = self._rerank_by_threat_context(matched, threat_hints)

        primary = matched[0]
        secondaries = matched[1:]
        return {
            "profile": profile,
            "primary": primary,
            "secondaries": [
                {
                    "id": s["id"],
                    "title": s["title"],
                    "level": s["level"],
                    "level_label": s["level_label"],
                    "category_name": s["category_name"],
                    "statement": s["statement"],
                    "risk_statement": s["risk_statement"],
                    "recommendation": s["recommendation"],
                }
                for s in secondaries
            ],
            "secondary_count": len(secondaries),
            "label": f"[SSP: {primary['id']}]",
        }

    def _rerank_by_threat_context(self, candidates: list, threat_hints: dict) -> list:
        """
        Reorder candidates so the most contextually relevant SSP control is first,
        while still respecting level ordering within the same affinity score.

        Affinity is scored by how well the SSP category prefix matches the
        threat categories (rapids_threats) and DIR category of the recommendation.
        """
        preferred_prefixes: list[str] = []
        for t in (threat_hints.get("rapids_threats") or []):
            preferred_prefixes.extend(self._THREAT_CATEGORY_AFFINITY.get(t, []))
        dir_cat = (threat_hints.get("dir_category") or "").lower()
        preferred_prefixes.extend(self._DIR_AFFINITY.get(dir_cat, []))

        if not preferred_prefixes:
            return candidates

        def _score(c: dict) -> tuple:
            cat = c.get("category", "").lower()
            affinity = preferred_prefixes.index(cat) if cat in preferred_prefixes else len(preferred_prefixes)
            return (affinity, c["level"])

        return sorted(candidates, key=_score)

    def _lookup_ssp_controls(self, control_name: str, profile: str) -> list:
        """
        Return SSP controls for a control name under the given profile,
        sorted by level ascending (most mandatory first).

        Falls back to keyword matching when no exact name match exists.
        """
        # Exact name match
        candidate_ids = self._mappings.get(control_name)

        # Keyword fallback
        if not candidate_ids:
            for keyword, ids in self._keywords.items():
                if keyword in control_name:
                    candidate_ids = ids
                    break

        if not candidate_ids:
            return []

        results = []
        for cid in candidate_ids:
            control_record = self._controls.get(cid)
            if not control_record:
                continue

            # Level for the requested profile
            level = self._profiles.get(cid, {}).get(profile)
            if level is None:
                level = 1  # default to L1 when not explicitly listed

            # Levels across ALL profiles — lets the frontend detect escalations
            # (e.g. AC-1 is L2 at low_risk_cloud but L1 at medium_risk_cloud).
            all_profile_levels = {
                p: self._profiles.get(cid, {}).get(p)
                for p in SSP_PROFILES
                if self._profiles.get(cid, {}).get(p) is not None
            }

            results.append({
                "id": cid,
                "catalog": control_record.get("catalog", "cybersecurity"),
                "category": control_record.get("category", ""),
                "category_name": control_record.get("category_name", ""),
                "title": control_record.get("title", ""),
                "statement": control_record.get("statement", ""),
                "recommendation": control_record.get("recommendation", ""),
                "risk_statement": control_record.get("risk_statement", ""),
                "level": level,
                "level_label": _LEVEL_LABELS.get(level, f"L{level}"),
                "levels_by_profile": all_profile_levels,  # {profile_name: level} for all known profiles
            })

        # Sort by level ascending so L0 (most mandatory) comes first
        results.sort(key=lambda x: x["level"])
        return results


# Module-level singleton — instantiated once on first import, shared across requests.
# Lazy-loaded via property pattern so import errors don't surface at module load time.
_mapper_instance: Optional[SspControlMapper] = None


def get_ssp_mapper() -> SspControlMapper:
    global _mapper_instance
    if _mapper_instance is None:
        _mapper_instance = SspControlMapper()
    return _mapper_instance
